## 📘 NumPy Array Generation Functions

In [1]:
import numpy as np

### 1. `np.array()`

Convert Python list/tuple into NumPy array.


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

### 2. `np.zeros()`

Creates an array filled with **0s**.


In [ ]:
"""
Visual:
   Col1  Col2  Col3
Row1   1     2     3
Row2   4     5     6
Row3   7     8     9
"""

In [ ]:
np.zeros((2, 3)) # 2- rows, 3 - columns

array([[0., 0., 0.],
       [0., 0., 0.]])

### 3. `np.ones()`

Creates an array filled with **1s**.


In [ ]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### 4. `np.full()`

Creates an array filled with a **specific value**.


In [ ]:
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

### 5. `np.arange()`

Creates an array with values in a **range (like Python range)**.


In [ ]:
np.arange(0, 10, 2)   # start=0, stop=10, step=2

array([0, 2, 4, 6, 8])

### 6. `np.linspace()`

Creates an array with **n evenly spaced values** between start and end.


In [ ]:
np.linspace(0, 1, 5) 
# range 0-1
# 5 number of elements we want now see the output
#linspace means linear_space

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 7. `np.eye()`

Creates an **identity matrix** (1s on diagonal).


In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 8. `np.random.rand()`

Creates an array of random numbers between **0 and 1**.


In [ ]:
np.random.rand(2, 3)
# As u can see in the output all the values between 0 & 1 this concept is know as normalization in statistics.
# Values between 3 to -3 - standarization
# Values between 0 to 1 - normalization 

array([[0.81112309, 0.51283409, 0.66393331],
       [0.64427735, 0.77132999, 0.86751424]])

### 9. `np.random.randint()`

Creates an array of random **integers** within a given range.


In [5]:
np.random.randint(1, 10, (2, 3))  # from 1 to 9

array([[9, 6, 7],
       [4, 4, 7]], dtype=int32)

## ⚡ Summary Table
| Function            | Description                          |
|---------------------|--------------------------------------|
| np.array()          | Convert list/tuple → array          |
| np.zeros()          | Array of 0s                         |
| np.ones()           | Array of 1s                         |
| np.full()           | Array with a constant value         |
| np.arange()         | Range with step (like Python range) |
| np.linspace()       | n evenly spaced values              |
| np.eye()            | Identity matrix                     |
| np.random.rand()    | Random floats (0 to 1)              |
| np.random.randint() | Random integers in a range          |