## 📘 NumPy Array Methods

In [1]:
import numpy as np

### 1. `reshape() → Shape Change`
Reshape an array without changing its data.

In [2]:
arr = np.arange(1, 7)   # [1, 2, 3, 4, 5, 6]
arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

### 2. `flatten()→ 1D Convert`
Converts a multi-dimensional array into 1D.


In [3]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
matrix.flatten()

array([1, 2, 3, 4, 5, 6])

### 3. `ravel() → 1D Convert (View)`
Also flattens array, but returns a **view (no copy if possible)**.


In [4]:
matrix.ravel()

array([1, 2, 3, 4, 5, 6])

### 4. `transpose()` or `.T`
Switches rows and columns.


In [5]:
matrix.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

### 5. `sum() → Total / Along Axis`
Returns sum of elements (overall or axis-wise).


In [ ]:
np.sum(matrix,axis=0)
# column-wise sum
"""
array([[1, 2, 3],
       [4, 5, 6]])
1 + 4 = 5
2 + 5 = 7
3 + 6 = 9
"""


array([5, 7, 9])

In [15]:
a = np.sum(matrix,axis=1)
# row-wise sum
'''
array([[1, 2, 3],
       [4, 5, 6]])
1 + 2 + 3 = 6
4 + 5 + 6 = 15
'''
a

array([ 6, 15])

### 6. `min()` and `max()`
Returns smallest and largest element.


In [23]:
print(f"Min value = {matrix.min()}")
print(f"Max value = {matrix.max()}")


Min value = 1
Max value = 6


### 7. `argmin()` and `argmax()`
Returns index of min and max element.


In [28]:
print(f"Minimum value in array is at {matrix.argmin()} index")
print(f"Maximun value in array is at {matrix.argmax()} index")

Minimum value in array is at 0 index
Maximun value in array is at 5 index


In [29]:
# Combining both 

# Find indices
min_index = matrix.argmin()
max_index = matrix.argmax()

# Find values
min_value = matrix.min()
max_value = matrix.max()

print(f"Minimum value in array is {min_value} at index {min_index}")
print(f"Maximum value in array is {max_value} at index {max_index}")

Minimum value in array is 1 at index 0
Maximum value in array is 6 at index 5


### 8. `mean()`
Average of array elements.


In [33]:
print(f"Matrix mean value ={matrix.mean()}")


Matrix mean value =3.5


### 9. `sort()`
Returns a sorted copy of the array.


In [38]:
a = np.array([3, 1, 4, 2])
a.sort()   # sorts in-place
print(a)

[1 2 3 4]


In [ ]:
a = np.array([3, 1, 4, 2])
b = np.sort(a)   # returns new sorted array
print(b)

[1 2 3 4]


In [ ]:
'''
👉 Rule yaad rakho:

np.sort(arr) → new sorted array return karta hai

arr.sort() → inplace sort karta hai, but returns None
'''

### 10. `copy()` vs `view()`
- `copy()` → Creates new independent array.
- `view()` → Creates a new view (changes reflect in original).


In [41]:
a = np.array([1, 2, 3])
b = a.copy()
c = a.view()

a[0] = 99
print(a)
print(b)
print(c)

[99  2  3]
[1 2 3]
[99  2  3]


✅ Summary
| Method        | Use Case                          |
|---------------|-----------------------------------|
| reshape()     | Change shape                     |
| flatten()     | Convert to 1D (copy)             |
| ravel()       | Convert to 1D (view)             |
| transpose()   | Switch rows & columns            |
| sum()         | Total / row-wise / col-wise sum  |
| min(), max()  | Smallest & largest value         |
| argmin(),argmax() | Index of min & max value     |
| mean()        | Average                          |
| sort()        | Sort array                       |
| copy(), view()| Copy vs reference                |
