## 📘 Reshaping vs Resizing in NumPy

In [1]:
import numpy as np

### 1. `reshape() → Change Shape (without changing data)`
- Returns a new array with a different shape.
- Total number of elements must remain the same.
- Does not modify the original array.


In [ ]:
arr = np.arange(1, 31)   #generates num 1-30
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
# before performing reshape we should know the shape of array
arr.shape
# means there are 30 values
# so 5 rows x 5 columns = 25 (not possible)
# 6 rows X 5 columns = 30 (possible)

(30,)

In [7]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### 2. `np.resize() (function) → Change Shape, Repeat/Truncate Data`
- Changes the shape of array.
- If new size > old size → repeats data.
- If new size < old size → truncates data.


In [8]:
arr = np.array([1, 2, 3, 4])
resized = np.resize(arr, (3, 3))

print("Original:", arr)
print("Resized:\n", resized)

Original: [1 2 3 4]
Resized:
 [[1 2 3]
 [4 1 2]
 [3 4 1]]


### 3. `arr.resize() (method) → In-place Resize`
- Works like `np.resize()`.
- Modifies the original array directly (in-place).


In [9]:
arr = np.array([1, 2, 3, 4])
arr.resize((2, 2))
print(arr)

[[1 2]
 [3 4]]


✅ Summary
| Function        | Works how?                            | Allows size change? | Returns new array? |
|-----------------|---------------------------------------|---------------------|--------------------|
| reshape()       | Change shape (same data size only)    | ❌ No               | ✅ Yes (view/copy) |
| np.resize()     | Change shape, repeat/truncate values  | ✅ Yes              | ✅ Yes             |
| arr.resize()    | Same as np.resize but in-place        | ✅ Yes              | ❌ No (in-place)   |
