--- 🔹 7. Cumulative Operations

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4])

print("Cumulative Sum:", np.cumsum(arr))   # [ 1  3  6 10]
print("Cumulative Product:", np.cumprod(arr)) # [ 1  2  6 24]

Cumulative Sum: [ 1  3  6 10]
Cumulative Product: [ 1  2  6 24]


--- 🔹 8. Rounding Functions

In [3]:
arr = np.array([1.2, 2.5, 3.7])

print("Floor:", np.floor(arr))   # [1. 2. 3.]
print("Ceil:", np.ceil(arr))     # [2. 3. 4.]
print("Round:", np.round(arr))   # [1. 2. 4.]

Floor: [1. 2. 3.]
Ceil: [2. 3. 4.]
Round: [1. 2. 4.]


---🔹 9. Stacking Arrays

👉 Join multiple arrays together (vertically or horizontally).

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Vertical Stack:\n", np.vstack((a, b)))
print("Horizontal Stack:\n", np.hstack((a, b)))
print("Column Stack:\n", np.column_stack((a, b)))


Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]
Column Stack:
 [[1 4]
 [2 5]
 [3 6]]


--- 🔹 10. Splitting Arrays

👉 Break an array into smaller chunks.

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])

print("Split into 3 parts:", np.split(arr, 3))
print("Split at indices [2,4]:", np.split(arr, [2, 4]))


Split into 3 parts: [array([1, 2]), array([3, 4]), array([5, 6])]
Split at indices [2,4]: [array([1, 2]), array([3, 4]), array([5, 6])]


--- 🔹 11. Advanced Array Manipulation

In [6]:
arr = np.arange(9).reshape(3, 3)

print("Original:\n", arr)
print("Transpose:\n", arr.T)            # swap rows and cols
print("Flatten:\n", arr.flatten())      # convert to 1D
print("Ravel:\n", arr.ravel())          # 1D view (faster)
print("Rotate 90°:\n", np.rot90(arr))   # rotate matrix
print("Flip LR:\n", np.fliplr(arr))     # flip left-right
print("Flip UD:\n", np.flipud(arr))     # flip up-down

Original:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Transpose:
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
Flatten:
 [0 1 2 3 4 5 6 7 8]
Ravel:
 [0 1 2 3 4 5 6 7 8]
Rotate 90°:
 [[2 5 8]
 [1 4 7]
 [0 3 6]]
Flip LR:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]
Flip UD:
 [[6 7 8]
 [3 4 5]
 [0 1 2]]


--- 🔹 12. Copying Arrays (Shallow vs Deep Copy)

In [7]:
a = np.array([1, 2, 3])

# Shallow Copy (View) - shares memory
b = a.view()
b[0] = 100
print("a (after b change):", a)   # a also changes

# Deep Copy - independent copy
c = a.copy()
c[1] = 200
print("a (after c change):", a)   # a does not change


a (after b change): [100   2   3]
a (after c change): [100   2   3]


✅ Summary
| **Category**              | **Functions / Examples**                              | **Notes**                               |
|--------------------------|--------------------------------------------------------|------------------------------------------|
| **Cumulative**            | `np.cumsum(arr)`, `np.cumprod(arr)`                    | Running sum/product                      |
| **Rounding**              | `np.floor()`, `np.ceil()`, `np.round()`                | Floor ↓, Ceil ↑, Round to nearest        |
| **Stacking**              | `np.vstack()`, `np.hstack()`, `np.column_stack()`      | Join arrays vertically/horizontally      |
| **Splitting**             | `np.split(arr, 3)`, `np.split(arr, [2, 4])`            | Equal or index-based split               |
| **Advanced Manipulation** | `flatten()`, `ravel()`, `rot90()`, `fliplr()`, `flipud()` | Reshape, rotate, flip                 |
| **Copying**               | `a.view()` (shallow), `a.copy()` (deep)                | View shares data, Copy is independent    |

