# 📝 NumPy – Array Operations (Full Notes)

---🔹 1. Arithmetic Operations (Element-wise)

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)         # [5 7 9]
print("Subtraction:", a - b)      # [-3 -3 -3]
print("Multiplication:", a * b)   # [ 4 10 18]
print("Division:", a / b)         # [0.25 0.4 0.5]
print("Power:", a ** 2)           # [1 4 9]


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Power: [1 4 9]


--- 🔹 2. Scalar Operations

In [2]:
arr = np.array([1, 2, 3])

print(arr + 10)   # [11 12 13]
print(arr * 2)    # [2 4 6]

[11 12 13]
[2 4 6]


---🔹 3. Comparison & Logical Operations

In [3]:
a = np.array([1, 2, 3, 4])

print(a > 2)       # [False False  True  True]
print(np.any(a > 3))   # True
print(np.all(a > 0))   # True

[False False  True  True]
True
True


--- 🔹 4. Matrix Operations (2D)

In [4]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix Addition:\n", A + B)
print("Matrix Multiplication (element-wise):\n", A * B)
print("Dot Product:\n", A @ B)   # OR np.dot(A, B)

Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication (element-wise):
 [[ 5 12]
 [21 32]]
Dot Product:
 [[19 22]
 [43 50]]


--- 🔹 5. Broadcasting

In [5]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(A + b)

[[11 22 33]
 [14 25 36]]


--- 🔹 6. Aggregate Functions

In [6]:
arr = np.array([1, 2, 3, 4])

print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())
print("Std Dev:", arr.std())

Sum: 10
Mean: 2.5
Max: 4
Min: 1
Std Dev: 1.118033988749895


✅ Summary
| **Category**              | **Functions / Examples**                              | **Notes**                               |
|--------------------------|--------------------------------------------------------|------------------------------------------|
| **Arithmetic & Scalar**   | `a + b`, `a - b`, `a * b`, `a / b`, `a ** 2`, `a + 10`, `a * 2` | Element-wise operations & scalar ops     |
| **Comparison & Logical**  | `a > 2`, `a == 3`, `np.any(a > 3)`, `np.all(a > 0)`    | Returns boolean arrays                   |
| **Matrix Ops**            | `A + B`, `A * B`, `A @ B`, `A.T`                       | Dot product: `@` or `np.dot()`           |
| **Broadcasting**          | `A + b`                                                | Automatically expands smaller shape      |
| **Aggregate**             | `sum()`, `mean()`, `max()`, `min()`, `std()`           | Applies to full array or along an axis   |
