## 📘 NumPy Indexing & Slicing (2D Arrays / Matrices)

In [1]:
import numpy as np

### 1. `Basic Indexing`
- Syntax: arr[row, col]
- Works like accessing rows & columns in a grid.


In [2]:
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

print(matrix[0, 0])   # element at 1st row, 1st col
print(matrix[1, 2])   # element at 2nd row, 3rd col
print(matrix[-1, -1]) # last element


10
60
90


### 2. `Row & Column Access`
- Use `:` to select entire row/column.


In [3]:
print(matrix[0, :])   # 1st row
print(matrix[:, 1])   # 2nd column


[10 20 30]
[20 50 80]


### 3. `Slicing Sub-matrices`
- Syntax: arr[row_start:row_end , col_start:col_end]


In [4]:
print(matrix[0:2, 1:3])   # top-left 2x2 block (rows 0-1, cols 1-2)

[[20 30]
 [50 60]]


### 4. `Fancy Indexing`
- Select multiple rows/columns using lists of indices.

In [5]:
print(matrix[[0, 2], [1, 2]])   # (0,1) and (2,2)
print(matrix[[0, 2], :])        # rows 0 and 2

[20 90]
[[10 20 30]
 [70 80 90]]


### 5. `Boolean Indexing`
- Apply conditions to filter values in matrix.

In [6]:
print(matrix[matrix > 50])   # all elements greater than 50

[60 70 80 90]


✅ Summary
| Type                  | Example                   | Meaning                                    |
|-----------------------|---------------------------|--------------------------------------------|
| Single element        | matrix[1,2]              | element at 2nd row, 3rd col                |
| Row access            | matrix[0, :]             | full 1st row                               |
| Column access         | matrix[:, 1]             | full 2nd column                            |
| Sub-matrix slicing    | matrix[0:2, 1:3]         | rows 0-1, cols 1-2                         |
| Fancy indexing        | matrix[[0,2], [1,2]]     | elements at (0,1) & (2,2)                  |
| Boolean indexing      | matrix[matrix>50]        | filter values greater than 50              |