## 📘 NumPy Indexing & Slicing (vectors (1D arrays)).

In [1]:
import numpy as np

### 1. `Indexing in NumPy`
- Indexing starts from 0 (like Python lists).
- Negative indexing is allowed (from the end).
- Syntax: arr[index]

In [2]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])   # First element
print(arr[2])   # Third element
print(arr[-1])  # Last element


10
30
50


### 2. `Slicing in NumPy`
- Access a range of elements.
- Syntax: arr[start:end:step]
- Default:
  start = 0
  end = length of array
  step = 1


In [3]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

print(arr[1:5])     # elements from index 1 to 4
print(arr[:4])      # first 4 elements
print(arr[3:])      # from index 3 to end
print(arr[::2])     # every 2nd element
print(arr[::-1])    # reverse array


[20 30 40 50]
[10 20 30 40]
[40 50 60 70]
[10 30 50 70]
[70 60 50 40 30 20 10]


### 3. `Fancy Indexing`
- Pass a list/array of indices to access multiple elements at once.


In [5]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[[0, 2, 4]])   # elements at index 0,2,4

[10 30 50]


### 4. `Boolean Indexing`
- Use conditions to filter elements.

In [6]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 25])     # elements greater than 25
print(arr[arr % 20 == 0])  # multiples of 20

[30 40 50]
[20 40]


✅ Summary
| Type             | Syntax / Example         | Meaning                          |
|------------------|--------------------------|----------------------------------|
| Indexing         | arr[2]                  | Single element (3rd element)     |
| Negative index   | arr[-1]                 | Last element                     |
| Slicing          | arr[1:5:2]              | From index 1 to 4, step 2        |
| Reverse slicing  | arr[::-1]               | Reverse array                    |
| Fancy indexing   | arr[[0,2,4]]            | Elements at indices 0,2,4        |
| Boolean indexing | arr[arr>25]             | Filter using condition           |